### ISSUE TITLE
如何获取一个请求的耗时呢?

### ISSUE THREAD

**Issue by wenber-yu** [friendsofhyperf/http-client#2]
一个请求比如我设置的超时时间是3秒, 重试5次, 如果在请求成功或者失败时, 获取到这次请求的耗时呢

**Comment by huangdijia** [comment]
```php
$response = Http::get('https://www.baidu.com');
var_dump($response->transferStats?->getTransferTime());
```

**Comment by wenber-yu** [comment]
使用该方法提示未定义
`Call to undefined method GuzzleHttp\\Psr7\\Response::transferStats()`
```php
public function request(string $method, string $url, array $params, bool $isAuth = true)
{
	try {
	    $http = Http::asJson()->baseUrl(self::$config['base_url'])->acceptJson();
	    if ($isAuth) {
	        $http = $http->withHeaders(headers: [
	            'Authori-zation' => 'Bearer '.$this->getToken(),
	        ]);
	    }
	    $response = $http->timeout(5)->retry(3)->$method($url, $params);
	    $result = $response->throw()->json();
	}  finally {
	    $data = [
	        'url' => self::$config['base_url'].$url,
	        'type' => ExternalApiRequestLogConstant::TYPE_NC,
	        'status' => $status,
	        'request' => [
	            'method' => $method,
	            'options' => $http->mergeOptions(),
	            'data' => $params,
	        ],
	        'response' => $result ?? [],
	        'transfer_time' => $response->transferStats()?->getTransferTime(),
	    ];
	    di(ExternalApiRequestLogService::class)->record($data);
	}
}
```

**Comment by huangdijia** [comment]
是不是哪里没用对？$response 不应该是 GuzzleHttp\\Psr7\\Response

**Comment by wenber-yu** [comment]
我把请求方法改成send后,
<img width="1305" alt="image" src="https://user-images.githubusercontent.com/7148309/206738881-97186df2-fd29-4562-97a7-0ea157c52df0.png">
看ide提示, 响应类是两个, 但是我看代码, 确实是不会返回GuzzleHttp\Psr7\Response

**Comment by huangdijia** [comment]
不太了解phpstorm，我用vscode正常

**Comment by wilbur-yu** [comment]
> 我把请求方法改成send后, <img alt="image" width="1305" src="https://user-images.githubusercontent.com/7148309/206738881-97186df2-fd29-4562-97a7-0ea157c52df0.png"> 看ide提示, 响应类是两个, 但是我看代码, 确实是不会返回GuzzleHttp\Psr7\Response
现在改成这样调用, 把`$response`打印出来后是:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/7148309/206849985-8598785c-bdb4-4d14-baf8-6c02ac1158f1.png">
$response->transferStats属性中没有getTransferTime()方法, 我试着直接访问`transferTime`属性也不可以, 是私有属性

**Comment by wenber-yu** [comment]
可以了, 是我看错了, 您写的是直接访问属性, 我写成方法了. 所以一直没有访问到.
但是有个没太理解的地方, 我将`$response`打印出来看对象结构时为:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/7148309/206850510-69f1bb81-269d-4e14-972d-718d8ddeedaf.png">
有一个`transferTime `私有属性, 但是没有看到`getTransferTime()`方法

**Comment by huangdijia** [comment]
用IDE应该能跳转到 getTransferTime()方法
